<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Застройщики");
$APPLICATION->SetPageProperty("description", "Список партнёрских строительных компаний — застройщиков домов и коттеджей от «Земельный экспресс».");
$APPLICATION->SetPageProperty("title", "Застройщики — партнёрские строительные компании по строительству домов");
?><?$APPLICATION->IncludeComponent(
    "bitrix:news",
    "builders",
    Array(
        "IBLOCK_TYPE" => "content",
        "IBLOCK_ID" => "68",
        "NEWS_COUNT" => "20",
        "SORT_BY1" => "SORT",
        "SORT_BY2" => "NAME",
        "SORT_ORDER1" => "ASC",
        "SORT_ORDER2" => "ASC",
        "LIST_FIELD_CODE" => array(0=>"DETAIL_PICTURE",),
        "LIST_PROPERTY_CODE" => array(0=>"LOGO",1=>"PHONE",2=>"EXPERIENCE",3=>"HOUSES_COUNT",4=>"REGION",),
        "DETAIL_FIELD_CODE" => array(0=>"DETAIL_PICTURE",),
        "DETAIL_PROPERTY_CODE" => array(0=>"LOGO",1=>"PHONE",2=>"EMAIL",3=>"WEBSITE",4=>"EXPERIENCE",5=>"HOUSES_COUNT",6=>"REGION",7=>"GALLERY",),
        "DETAIL_URL" => "/zastrojshhiki/#ELEMENT_CODE#/",
        "SEF_MODE" => "Y",
        "SEF_FOLDER" => "/zastrojshhiki/",
        "SEF_URL_TEMPLATES" => array("news"=>"","section"=>"","detail"=>"#ELEMENT_CODE#/",),
        "SET_TITLE" => "Y",
        "SET_LAST_MODIFIED" => "N",
        "MESSAGE_404" => "",
        "SET_STATUS_404" => "Y",
        "SHOW_404" => "Y",
        "FILE_404" => "/404.php",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "CACHE_TYPE" => "N",
        "CACHE_TIME" => "3600",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "N",
        "DISPLAY_TOP_PAGER" => "N",
        "DISPLAY_BOTTOM_PAGER" => "N",
        "DETAIL_DISPLAY_TOP_PAGER" => "N",
        "DETAIL_DISPLAY_BOTTOM_PAGER" => "N",
        "PAGER_TITLE" => "Застройщики",
        "PAGER_TEMPLATE" => "news",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "DISPLAY_DATE" => "N",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PICTURE" => "Y",
        "DISPLAY_PREVIEW_TEXT" => "Y",
        "PREVIEW_TRUNCATE_LEN" => "",
        "ACTIVE_DATE_FORMAT" => "d.m.Y",
        "USE_PERMISSIONS" => "N",
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "CHECK_DATES" => "Y",
        "ADD_ELEMENT_CHAIN" => "Y",
        "COMPONENT_TEMPLATE" => "builders",
        "USE_FILTER" => "N",
        "USE_SEARCH" => "N",
    )
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
